### ISSUE TITLE
Settings management: Customize root directory

### ISSUE THREAD

**Issue by crippa9** [noteron/noetter#2]

**Comment by Wholteza** [comment]
Place to put settings was provided by @crippa9  in issue #3 
Need to make the path actually change the root path.
As well as providing an option to copy all the existing files to that new path, or just change path.

![image](https://user-images.githubusercontent.com/6461166/94359595-a359a900-00a8-11eb-9341-4e440cea3466.png)

**Comment by Wholteza** [comment]
![image](https://user-images.githubusercontent.com/6461166/94359586-99d04100-00a8-11eb-9b66-0090caaa9eef.png)
